export const maniCasadonaOptions = [
  {
    id: 1,
    name: "3rd Floor Office",
    folder: "3rd floor office",
    size: "1052 sq.ft",
    workstation: 16,
    cabin: 2,
    conferenceRoom: 1,
    reception: "Yes",
    pantry: "Yes",
    carParking: 1,
    rent: "65 K onwards",
    images: ["10.jpg", "11.jpg", "12.jpg", "13.jpg", "14.jpg", "8.jpg", "9.jpg"]
  },
  {
    id: 2,
    name: "3rd Floor",
    folder: "3rd floor",
    size: "900 sq.ft",
    workstation: 10,
    cabin: 1,
    conferenceRoom: 1,
    reception: "Yes",
    pantry: "Yes",
    carParking: 1,
    rent: "55 K onwards",
    images: ["10.jpg", "11.jpg", "13.jpg", "14.jpg", "15.jpg", "16.jpg", "18.jpg", "5.jpg", "6.jpg", "7.jpg", "8.jpg"]
  },
  {
    id: 3,
    name: "4th Floor Office",
    folder: "4th floor office",
    size: "1127 sq.ft",
    workstation: 18,
    cabin: 2,
    conferenceRoom: 0,
    reception: "Yes",
    pantry: "Yes",
    carParking: 1,
    rent: "70 K onwards",
    images: ["10.jpg", "11.jpg", "4.jpg", "5.jpg", "6.jpg", "7.jpg", "8.jpg", "9.jpg"]
  },
  {
    id: 4,
    name: "6th Floor N",
    folder: "6th floor n",
    size: "623 sq.ft",
    workstation: 8,
    cabin: 1,
    conferenceRoom: 1,
    reception: "Yes",
    pantry: "Yes",
    carParking: 1,
    rent: "50 K onwards",
    images: ["18.jpg", "19.jpg", "20.jpg", "21.jpg", "22.jpg", "23.jpg", "24.jpg", "25.jpg", "26.jpg"]
  },
  {
    id: 5,
    name: "6th Mani",
    folder: "6th Mani",
    size: "807 sq.ft",
    workstation: 13,
    cabin: 1,
    conferenceRoom: 1,
    reception: "Yes",
    pantry: "Yes",
    carParking: 1,
    rent: "60 K onwards",
    images: ["1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg", "7.jpg"]
  },
  {
    id: 6,
    name: "7th Floor Office",
    folder: "7th floor office",
    size: "525 sq.ft",
    workstation: 10,
    cabin: 1,
    conferenceRoom: 0,
    reception: "Yes",
    pantry: "Yes",
    carParking: 1,
    rent: "40 K onwards",
    images: ["1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg", "7.jpg", "8.jpg"]
  },
  {
    id: 7,
    name: "11th Floor Office",
    folder: "11th floor office",
    size: "1550 sq.ft",
    workstation: 30,
    cabin: 2,
    conferenceRoom: 1,
    reception: "Yes",
    pantry: "Yes",
    carParking: 1,
    rent: "1.15 lac onwards",
    images: ["1.jpg", "10.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg", "7.jpg", "8.jpg", "9.jpg"]
  },
  {
    id: 8,
    name: "Premium Option 8",
    folder: "Option 8",
    size: "4700 sq.ft",
    workstation: 100,
    cabin: 7,
    conferenceRoom: 2,
    reception: "Yes",
    pantry: "Yes",
    carParking: 1,
    rent: "3 lac onwards",
    images: ["10.jpg", "11.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg", "7.jpg", "8.jpg", "9.jpg"]
  }
];
